language: node
node_js:
    - "node"
    - "6"
    - "6.0"

sudo: false

before_script:
    # Install Grunt
    - npm install -g grunt-cli
    # Install dependancies
    - npm install

script:
    - grunt prod
